[package]
name = "plan"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
bench = false

[dependencies]
execute = { path = "../execute" }
graphql-ir = { path = "../graphql/ir" }
metadata-resolve = {path = "../metadata-resolve" }
open-dds = { path = "../open-dds" }

derive_more = { workspace = true }
indexmap = { workspace = true, features = ["serde"] }


[lints]
workspace = true
