[package]
name = "json-ext"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
bench = false

[dependencies]

serde = "1.0.152"
serde_json = "1.0.116"

[lints]
workspace = true
