[package]
name = "lang-graphql"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
bench = false

[[bench]]
name = "lexer"
harness = false

[[bench]]
name = "parser"
harness = false

[[bench]]
name = "validation"
harness = false

[[bench]]
name = "schema_serde"
harness = false

[dependencies]
recursion_limit_macro = { path = "../utils/recursion_limit_macro" }

axum = "0.6.20"
http = "0.2"
indexmap = { version = "2", features = ["serde"] }
lexical-core = "0.8"
nonempty = { version = "0.10", features = ["serialize"] }
schemars = { version = "0.8.20", features = ["smol_str"] }
serde = "1.0.202"
serde_json = "1.0.116"
serde_with = "3.8.1"
smol_str = "0.1.23"
thiserror = "1.0"

[dev-dependencies]
apollo-parser = "0.7"
async-graphql-parser = "7.0"
bincode = "1.3.3"
bson = "2.10.0"
criterion = { version = "0.5", features = ["html_reports"] }
diffy = "0.3.0"
expect-test = "1.5"
graphql-parser = "0.4"
human_bytes = "0.4.1"
postcard = { version = "1.0.4", features = ["use-std"] }
pretty_assertions = "1.3.0"
rmp-serde = "1.3.0"

[lints]
workspace = true
