[package]
name = "hasura-authn-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
bench = false

[dependencies]
lang-graphql = { path = "../lang-graphql" }
open-dds = { path = "../open-dds" }

axum = "0.6.20"
http = "0.2"
schemars = "0.8.12"
serde = "1.0.183"
thiserror = "1.0"

[dev-dependencies]
pretty_assertions = "1.3.0"

[lints]
workspace = true
