[package]
name = "recursion_limit_macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true
bench = false

[dependencies]
quote = "1"
syn = { version = "2", features = ["full"] }

[lints]
workspace = true
