[package]
name = "schema"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
bench = false

[[bin]]
name = "build-schema-from-metadata"
path = "bin/build-schema-from-metadata/main.rs"
bench = false

[dependencies]
hasura-authn-core = { path = "../auth/hasura-authn-core" }
json-ext = { path = "../utils/json-ext" }
lang-graphql = { path = "../lang-graphql" }
open-dds = { path = "../open-dds" }
metadata-resolve = {path = "../metadata-resolve" }

serde = "1.0.203"
serde_json = "1.0.117"
strum_macros = "0.26.3"
thiserror = "1.0"
insta = "1.39.0"

[lints]
workspace = true
