[package]
name = "query-usage-analytics"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
bench = false

[dependencies]
open-dds = { path = "../open-dds" }
metadata-resolve = { path = "../metadata-resolve" }

serde = { workspace = true }
serde_json = { workspace = true }

[lints]
workspace = true
