# Exclude this crate from the repo workspace
[workspace]
# this does not use the root properties so it can be built standalone
package.version = "0.1.0"
package.edition = "2021"
package.license = "Apache-2.0"

[package]
name = "hasura-dev-auth-webhook"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "hasura-dev-auth-webhook"
path = "src/main.rs"
bench = false

[dependencies]
tracing-util = { path = "../../tracing-util" }

anyhow = "1"
axum = "0.6.20"
http = "0.2"
serde_json = "1.0.108"
tokio = { version = "1.34.0", features = ["full"] }
tracing = "0.1.40"
tower-http = { version = "0.4.4", features = ["trace"] }
