[package]
name = "futures-ext"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
bench = false

[dependencies]
futures-util = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "time"] }

[lints]
workspace = true
