[package]
name = "engine"
version.workspace = true
edition.workspace = true
license.workspace = true

build = "build.rs"

[lib]
bench = false

[[bin]]
name = "engine"
path = "bin/engine/main.rs"
bench = false

[[bench]]
name = "execute"
harness = false

[[bench]]
name = "generate_ir"
harness = false

[dependencies]
hasura-authn-core = { path = "../hasura-authn-core" }
hasura-authn-jwt = { path = "../hasura-authn-jwt" }
hasura-authn-webhook = { path = "../hasura-authn-webhook" }
lang-graphql = { path = "../lang-graphql" }
open-dds = { path = "../open-dds" }
opendds-derive = { path = "../opendds-derive" }
tracing-util = { path = "../tracing-util" }

anyhow = "1"
async-recursion = "1.0.5"
axum = { version = "0.6.20" }
base64 = "0.22.0"
bincode = "1.3.3"
bytes = "1.6.0"
clap = { version = "4", features = ["derive", "env"] }
derive_more = "0.99.17"
futures-util = "0.3"
indexmap = { version = "2", features = ["serde"] }
json_value_merge = "2.0"
lazy_static = "1.4.0"
ndc-models = { git = "https://github.com/hasura/ndc-spec.git", tag = "v0.1.2" }
nonempty = "0.10"
reqwest = { version = "0.11", features = ["json", "multipart"] }
schemars = { version = "0.8.12", features = ["smol_str"] }
serde = "1.0.152"
serde_json = "1.0.92"
serde_path_to_error = "0.1.14"
strum = "0.26.2"
strum_macros = "0.25.2"
thiserror = "1.0"
tokio = { version = "1.26.0", features = [
  "macros",
  "parking_lot",
  "rt-multi-thread",
  "signal",
] }
tower-http = { version = "0.4", features = ["trace", "cors", "fs"] }
transitive = "0.5.0"
url = "2.4.1"

# Dependencies to build and run build.rs file
[build-dependencies]
build-data = "0.1.5" # To set short commit-sha at build time

[dev-dependencies]
criterion = { version = "0.4", features = ["html_reports", "async_tokio"] }
goldenfile = "1.4.5"
mockito = { version = "1.1.0", default-features = false, features = [] }
pretty_assertions = "1.3.0"
tokio-test = "0.4.2"

[package.metadata.cargo-machete]
ignored = [
  "build_data",          # cargo-machete ignores build dependencies
  "serde_path_to_error", # used by opendds-derive
  "strum",               # used by strum_macros
]

[lints]
workspace = true
