[package]
name = "engine"
version.workspace = true
edition.workspace = true
license.workspace = true

build = "build.rs"

[lib]
bench = false

[[bin]]
name = "engine"
path = "bin/engine/main.rs"
bench = false

[[bench]]
name = "execute"
harness = false

[dependencies]
execute = { path = "../execute" }
hasura-authn-core = { path = "../auth/hasura-authn-core" }
hasura-authn-jwt = { path = "../auth/hasura-authn-jwt" }
hasura-authn-webhook = { path = "../auth/hasura-authn-webhook" }
lang-graphql = { path = "../lang-graphql" }
open-dds = { path = "../open-dds" }
opendds-derive = { path = "../utils/opendds-derive" }
schema = { path = "../schema" }
tracing-util = { path = "../utils/tracing-util" }
metadata-resolve = {path = "../metadata-resolve" }

anyhow = "1"
axum = { version = "0.6.20" }
base64 = "0.22.1"
bincode = "1.3.3"
clap = { version = "4", features = ["derive", "env"] }
json_value_merge = "2.0"
reqwest = { version = "0.11", features = ["json", "multipart"] }
schemars = { version = "0.8.20", features = ["smol_str"] }
serde = "1.0.202"
serde_json = "1.0.116"
serde_path_to_error = "0.1.14"
thiserror = "1.0"
tokio = { version = "1.26.0", features = [
  "macros",
  "parking_lot",
  "rt-multi-thread",
  "signal",
] }
tower = "0.4"
tower-http = { version = "0.4", features = ["trace", "cors", "fs"] }

# Dependencies to build and run build.rs file
[build-dependencies]
build-data = "0.1.5" # To set short commit-sha at build time

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports", "async_tokio"] }
goldenfile = "1.7.1"
pretty_assertions = "1.3.0"
tokio-test = "0.4.2"

[package.metadata.cargo-machete]
ignored = [
  "build_data",          # cargo-machete ignores build dependencies
  "serde_path_to_error", # used by opendds-derive
]

[lints]
workspace = true
