[package]
name = "sql"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
execute = { path = "../execute" }
hasura-authn-core = { path = "../auth/hasura-authn-core" }
ir = { path = "../ir" }
metadata-resolve = {path = "../metadata-resolve" }
open-dds = { path = "../open-dds" }
schema = { path = "../schema" }
tracing-util = { path = "../utils/tracing-util" }

ndc-models = { workspace = true }
indexmap = { workspace = true }
datafusion = { version = "41", features = ["serde"] }
async-trait = "0.1.81"
futures = "0.3.30"
serde = { workspace = true, features = ["rc"] }
serde_json = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }

[lints]
workspace = true
