[package]
name = "execute"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
bench = false

[[bench]]
name = "generate_ir"
harness = false

[dependencies]
hasura-authn-core = { path = "../auth/hasura-authn-core" }
json-ext = { path = "../utils/json-ext" }
lang-graphql = { path = "../lang-graphql" }
open-dds = { path = "../open-dds" }
schema = { path = "../schema" }
tracing-util = { path = "../utils/tracing-util" }
metadata-resolve = {path = "../metadata-resolve" }
futures-ext = { path = "../utils/futures-ext" }

async-recursion = { workspace = true }
axum = { workspace = true }
base64 = { workspace = true }
bytes = { workspace = true }
derive_more = { workspace = true }
futures-util = { workspace = true }
indexmap = { workspace = true, features = ["serde"] }
ndc-models = { workspace = true }
nonempty = { workspace = true }
reqwest = { workspace = true, features = ["json", "multipart"] }
schemars = { workspace = true, features = ["smol_str"] }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["macros", "parking_lot", "rt-multi-thread", "signal"] }
transitive = { workspace = true }
url = { workspace = true }

[dev-dependencies]
criterion = { workspace = true, features = ["html_reports", "async_tokio"] }
goldenfile = { workspace = true }
mockito = { workspace = true }
pretty_assertions = { workspace = true }

[lints]
workspace = true
