[package]
name = "custom-connector"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
bench = false

[[bin]]
name = "custom-connector"
path = "src/main.rs"
bench = false

[dependencies]
anyhow = "1"
axum = { version = "0.6", features = ["http2"] }
env_logger = "0.11"
indexmap = "2"
ndc-models = { git = "https://github.com/hasura/ndc-spec.git", rev = "622c643b4f0b6bbe4601c0f065d6d93a4bd3e9db" }
regex = "1"
serde_json = "1"
serde = "1"
tokio = { version = "1", features = ["full"] }

[lints]
workspace = true
