[package]
name = "custom-connector"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
bench = false

[[bin]]
name = "custom-connector"
path = "src/main.rs"
bench = false

[dependencies]
anyhow = "1"
axum = { version = "0.6", features = ["http2"] }
env_logger = "0.11"
indexmap = "2"
ndc-models = { git = "https://github.com/hasura/ndc-spec.git", rev = "aa8ad48e42aefd9e585a4c923bebfd56eee40204" }
regex = "1"
serde_json = { version = "1", features = ["preserve_order"] }
serde = "1"
sha2 = "0.10.8"
tokio = { version = "1", features = ["full"] }

[lints]
workspace = true
